import argparse
from srrfiltermacs import srrfilter as sf
import os
import logging
from utils.loggerinitializer import * 
from distutils.dir_util import mkpath


mkpath(os.getcwd() + "/logs/")
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
initialize_logger(os.getcwd() + "/logs/", logger)


def main():

    print('Starting...')
    logger.info('Starting...')
    gse_count = sf.get_count(args.dataframe)
    gse_ihec = sf.filter_gse_count(gse_count, args.listgse)
    list_GSE_relaunch = sf.get_gse_rerun(gse_ihec, args.macs2pval, logger)
    sf.create_dir_data(list_GSE_relaunch, args.pathtogse)
    sf.move_srr(args.pathtogse,args.macs2pval, list_GSE_relaunch, logger)
    sf.move_paired(args.pathtogse,args.macs2pval, list_GSE_relaunch, logger)
    print('Script finished')
    logger.info('Script finished!')


if __name__ == "__main__":


    parser = argparse.ArgumentParser(

        description="A script to filter the SRR and GSEs that should be relaunched to IHEC pipeline"

    )

    parser.add_argument('-d', '--dataframe',
                        help='the absolut path to the dataframe with the metadata information including GSE and SRR column',
                        required=True)

    
    parser.add_argument('-l', '--listgse',
                        help='the absolut path to the txt file containing the desired GSEs',
                        required=True)


    parser.add_argument('-m', '--macs2pval',
                        help='the absolut path to the pval.bigwig files generated by macs2 step - IHEC pipeline')

    parser.add_argument('-p', '--pathtogse',
                        help='the absolut path to the GSE directories ')


    args=parser.parse_args()
    main()